### ISSUE TITLE
Public and Public_Files directory

### ISSUE THREAD

**Issue by Sell24** [metalsadman/quasar-laravel#8]
First thanks for taking the time to integrate both these projects together.

As for my question, as far as I can see these two directories and contents are identical and are related to Laravel. However, I am new to Quasar. So am I missing something and there is a reason to have both? Or should it just be public?

**Comment by metalsadman** [comment]
@Sell24 public is the target directory when you run `quasar build`, you can see it in your quasar.conf.js. since it recreates the folder every time you run the command that's why original contents (laravel related) from that folder is mirrored in public_files so that using CopyWebpackPlugin we can copy it back in the public folder after quasar has finished building. All can be seen in your quasar.conf.js file.

**Comment by Sell24** [comment]
Ok I get it. Instead of a dist directory on build you are using public_files and then copying it for us to public. That's great!

Thanks for the quick response and continued work.
